let BOUNDARIES=null;let MAP_POPUP_PBT='';
let DATA=[];let filtered=[];const $=id=>document.getElementById(id);const MONTHS=['Jan','Feb','Mac','Apr','Mei','Jun','Jul','Ogos','Sep','Okt','Nov','Dis'];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'}):'—';const count=(a,key)=>a.reduce((o,r)=>(o[r[key]]=(o[r[key]]||0)+1,o),{});const bar=(name,n,max)=>`<div class="barrow"><span title="${esc(name)}">${esc(name)}</span><div class="bartrack"><div class="barfill" style="width:${max?n/max*100:0}%"></div></div><b>${n}</b></div>`;const badge=s=>`<span class="pill ${s==='Ditolak'?'reject':s==='Tarik diri'?'withdraw':'wait'}">${esc(s)}</span>`;const detailBtn=r=>`<button class="link" data-case="${r.bil}">LR/2026/${String(r.bil).padStart(3,'0')}</button>`;const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}" class="empty">Tiada rekod untuk penapis ini</td></tr>`}</tbody></table></div>`;
function render(){let m=$('month').value,p=$('pbt').value,j=$('jenis').value;filtered=DATA.filter(r=>(!m||r.tarikhRayuan.slice(5,7)===m)&&(!p||r.pbt===p)&&(!j||r.jenis===j));let done=filtered.filter(r=>r.status!=='Belum ada keputusan');$('total').textContent=filtered.length;$('done').textContent=done.length;$('pending').textContent=filtered.length-done.length;$('hearing').textContent=filtered.filter(r=>r.pendengaran.length).length;let durations=done.filter(r=>r.keputusanTarikh.length&&r.tarikhRayuan).map(r=>(new Date(r.keputusanTarikh[0])-new Date(r.tarikhRayuan))/86400000).filter(n=>n>=0);$('duration').textContent=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length)+' hari':'—';$('timePanel').innerHTML=durations.length?`<div class="bigstat">${$('duration').textContent}</div><p class="subtle">Purata dari tarikh rayuan hingga tarikh keputusan untuk ${durations.length} rekod lengkap.</p>`:'<p class="empty">Tiada tarikh lengkap untuk pengiraan</p>';
const received=Array.from({length:12},(_,i)=>filtered.filter(r=>+r.tarikhRayuan.slice(5,7)===i+1).length),resolved=Array.from({length:12},(_,i)=>done.filter(r=>r.keputusanTarikh.some(d=>+d.slice(5,7)===i+1)).length);let max=Math.max(1,...received,...resolved),W=620,H=230,px=i=>40+i*49,py=n=>195-n/max*150;let grid=Array.from({length:5},(_,i)=>`<line x1="40" x2="610" y1="${py(max*i/4)}" y2="${py(max*i/4)}" stroke="#e1e8ef"/><text x="29" y="${py(max*i/4)+4}" font-size="11" fill="#68798e" text-anchor="end">${Math.round(max*i/4)}</text>`).join('');let path=a=>a.map((n,i)=>`${i?'L':'M'}${px(i)},${py(n)}`).join(' ');$('trend').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Trend rayuan bulanan">${grid}<path d="${path(received)}" fill="none" stroke="#cf1437" stroke-width="3"/><path d="${path(resolved)}" fill="none" stroke="#19a56e" stroke-width="3"/>${received.map((n,i)=>`<circle cx="${px(i)}" cy="${py(n)}" r="4" fill="#cf1437"><title>${MONTHS[i]}: ${n} diterima</title></circle>`).join('')}${resolved.map((n,i)=>`<circle cx="${px(i)}" cy="${py(n)}" r="4" fill="#19a56e"><title>${MONTHS[i]}: ${n} keputusan</title></circle>`).join('')}${MONTHS.map((v,i)=>`<text x="${px(i)}" y="216" font-size="11" fill="#65748b" text-anchor="middle">${v}</text>`).join('')}</svg>`;
let groups=count(filtered,'status'),d=groups['Ditolak']||0,t=groups['Tarik diri']||0,b=groups['Belum ada keputusan']||0,total=filtered.length||1,deg=x=>x/total*360;$('donut').innerHTML=`<div class="donut" style="background:conic-gradient(#d52e49 0deg ${deg(d)}deg,#3985d3 ${deg(d)}deg ${deg(d+t)}deg,#f1b63d ${deg(d+t)}deg 360deg)"><div class="donut-inner">${filtered.length}<small>Jumlah kes</small></div></div><div class="legend-list">🔴 Ditolak: <b>${d}</b><br>🔵 Tarik diri: <b>${t}</b><br>🟡 Belum ada keputusan: <b>${b}</b></div>`;let types=count(filtered,'jenis');$('types').innerHTML=Object.entries(types).sort((a,b)=>b[1]-a[1]).map(([k,v])=>bar(k,v,filtered.length)).join('')||'<p class="empty">Tiada rekod</p>';let pbts=count(filtered,'pbt');$('pbts').innerHTML=Object.entries(pbts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>bar(k,v,Math.max(1,...Object.values(pbts)))).join('')||'<p class="empty">Tiada rekod</p>';
let hearings=filtered.flatMap(r=>(r.pendengaran||[]).map(date=>({...r,date}))).sort((a,b)=>a.date.localeCompare(b.date));let hr=r=>`<tr><td>${fmt(r.date)}</td><td>${detailBtn(r)}</td><td>${esc(r.pbt)}</td><td>${esc(r.jenis)}</td><td>${badge(r.status)}</td></tr>`;$('upcoming').innerHTML=table(['Tarikh','No. Rayuan','PBT','Jenis','Status'],hearings.slice(0,5).map(hr));$('hearingTable').innerHTML=table(['Tarikh','No. Rayuan','PBT','Jenis','Status'],hearings.map(hr));let decisions=filtered.filter(r=>r.status!=='Belum ada keputusan');$('decisionTable').innerHTML=table(['No. Rayuan','PBT','Keputusan','Tarikh keputusan'],decisions.map(r=>`<tr><td>${detailBtn(r)}</td><td>${esc(r.pbt)}</td><td>${badge(r.status)}</td><td>${r.keputusanTarikh.map(fmt).join(', ')||'—'}</td></tr>`));let cats=[['Ditolak',d],['Tarik diri',t],['Belum ada keputusan',b]],highest=Math.max(1,...cats.map(x=>x[1]));$('decisionBars').innerHTML=`<div class="decisionbox">${cats.map(([k,v])=>`<div class="decisioncol"><b>${v}</b><div style="height:${Math.max(4,v/highest*125)}px"></div>${k}</div>`).join('')}</div>`;renderCases();renderPbtMap();}
function renderCases(){let q=$('search').value.toLocaleLowerCase();let a=filtered.filter(r=>[r.bil,r.pbt,r.jenis,r.status].join(' ').toLocaleLowerCase().includes(q));$('caseTable').innerHTML=table(['No. Rayuan','Tarikh Rayuan','Jenis Rayuan','PBT','Kategori','Status'],a.map(r=>`<tr><td>${detailBtn(r)}</td><td>${fmt(r.tarikhRayuan)}</td><td>${esc(r.jenis)}</td><td>${esc(r.pbt)}</td><td>${esc(r.jenis)}</td><td>${badge(r.status)}</td></tr>`));}
function showCase(bil){let r=DATA.find(r=>r.bil===+bil);if(!r)return;let fields=[['Tarikh Rayuan',fmt(r.tarikhRayuan)],['Pihak Berkuasa Tempatan',r.pbt],['Jenis Rayuan',r.jenis],['Status',r.status],['Tarikh Pendengaran',(r.pendengaran||[]).map(fmt).join(', ')||'—'],['Tarikh Keputusan',(r.keputusanTarikh||[]).map(fmt).join(', ')||'—']];$('detailBody').innerHTML=`<h2>LR/2026/${String(r.bil).padStart(3,'0')}</h2>${fields.map(([k,v])=>`<div class="detail-row"><b>${esc(k)}</b>${esc(v||'—')}</div>`).join('')}`;$('detail').showModal();}
function nav(page){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('hidden',e.id!==page));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===page));window.scrollTo(0,0)}
function exportCsv(){let fields=['bil','tarikhRayuan','pbt','jenis','status'];let csv='﻿'+[fields.join(','),...filtered.map(r=>fields.map(k=>'"'+String(r[k]||'').replace(/"/g,'""')+'"').join(','))].join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='rayuan-selangor-2026.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
fetch('data.json').then(r=>{if(!r.ok)throw Error('Gagal membaca data');return r.json()}).then(data=>{DATA=data;let ps=[...new Set(DATA.map(r=>r.pbt))].sort();ps.forEach(p=>$('pbt').add(new Option(p,p)));[...new Set(DATA.map(r=>r.jenis))].sort().forEach(j=>$('jenis').add(new Option(j,j)));MONTHS.forEach((m,i)=>$('month').add(new Option(m,String(i+1).padStart(2,'0'))));render();}).catch(e=>{$('overview').insertAdjacentHTML('afterbegin',`<p class="empty">${esc(e.message)}. Jalankan melalui pelayan web / GitHub Pages, bukan membuka fail HTML terus.</p>`)});document.querySelectorAll('.filters select').forEach(e=>e.addEventListener('change',()=>{if(e.target.id==='pbt')MAP_POPUP_PBT=e.target.value;render()}));$('reset').onclick=()=>{['month','pbt','jenis'].forEach(k=>$(k).value='');MAP_POPUP_PBT='';$('search').value='';render()};$('search').addEventListener('input',renderCases);document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.page));document.addEventListener('click',e=>{let b=e.target.closest('[data-case]');if(b)showCase(b.dataset.case);let n=e.target.closest('[data-goto]');if(n)nav(n.dataset.goto)});$('close').onclick=()=>$('detail').close();$('csv').onclick=exportCsv;


function showPbtPopup(code){const f=BOUNDARIES.features.find(x=>x.properties.code===code),el=$('mapPopup');if(!f||!el)return;const rows=filtered.filter(x=>x.pbt===code),status=count(rows,'status'),types=count(rows,'jenis');const months=Array.from({length:12},(_,i)=>rows.filter(x=>Number(x.tarikhRayuan.slice(5,7))===i+1).length),peak=Math.max(1,...months);const lines=obj=>Object.entries(obj).map(([k,v])=>'<div class="popup-line"><span>'+esc(k)+'</span><b>'+v+'</b></div>').join('');el.innerHTML='<button class="popup-close" id="closeMapPopup">Tutup ×</button><h3>'+esc(f.properties.name)+'</h3><div class="popup-total">'+rows.length+' <small>jumlah rayuan</small></div><h4>Status keputusan</h4>'+lines({'Ditolak':status['Ditolak']||0,'Tarik diri':status['Tarik diri']||0,'Belum ada keputusan':status['Belum ada keputusan']||0})+'<h4>Jenis rayuan</h4>'+(lines(types)||'<p>Tiada rekod</p>')+'<h4>Trend bulanan 2026</h4><div class="popup-trend">'+months.map((n,i)=>'<div class="popup-month"><div class="popup-track"><div style="height:'+(n/peak*100)+'%"></div></div><span>'+MONTHS[i]+'</span><b>'+n+'</b></div>').join('')+'</div><p class="muted">Berdasarkan bulan rayuan diterima dan penapis semasa.</p>';el.hidden=false;$('closeMapPopup').onclick=()=>{MAP_POPUP_PBT='';el.hidden=true}}
let LEAFLET_MAP=null,MAP_LAYER=null,MAP_FEATURES={};
function selectMapPbt(code){MAP_POPUP_PBT=code;$('pbt').value=code;render();if(code&&MAP_FEATURES[code]){LEAFLET_MAP.fitBounds(MAP_FEATURES[code].getBounds(),{padding:[25,25],maxZoom:11});showPbtPopup(code)}else if(LEAFLET_MAP)LEAFLET_MAP.fitBounds([[2.55,100.75],[3.85,102.05]])}
function renderPbtMap(){
 const host=$('pbtMap'),summary=$('pbtMapSummary');if(!host||!summary)return;
 if(!BOUNDARIES){host.textContent='Peta sedang dimuatkan…';return}
 const counts=count(filtered,'pbt'),max=Math.max(1,...Object.values(counts)),selected=$('pbt').value;
 if(!window.L){host.textContent='Pustaka peta tidak dapat dimuatkan. Semak sambungan internet.';return}
 if(!LEAFLET_MAP){
  LEAFLET_MAP=L.map(host,{zoomControl:true,scrollWheelZoom:true}).setView([3.18,101.47],9);
  const streets=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19});
  // EOX Sentinel-2 imagery replaces the previous Esri source completely.
  const satellite=L.tileLayer('https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2020_3857/default/g/{z}/{y}/{x}.jpg',{attribution:'Sentinel-2 cloudless © EOX IT Services GmbH (modified Copernicus Sentinel data 2020)',maxNativeZoom:14,maxZoom:19});
  satellite.on('tileerror',event=>{if(event.tile)event.tile.style.visibility='hidden';});
  satellite.addTo(LEAFLET_MAP);
  L.control.layers({'Satelit Sentinel-2':satellite,'Peta Jalan':streets},null,{position:'topright'}).addTo(LEAFLET_MAP);
  MAP_LAYER=L.geoJSON(BOUNDARIES,{style:()=>({color:'#ffffff',weight:1.8,fillOpacity:.42}),onEachFeature:(feature,layer)=>{const code=feature.properties.code;MAP_FEATURES[code]=layer;layer.on('click',()=>selectMapPbt(code));layer.on('mouseover',()=>layer.setStyle({weight:3,color:'#f6c453'}));layer.on('mouseout',()=>MAP_LAYER.resetStyle(layer))}}).addTo(LEAFLET_MAP);
  LEAFLET_MAP.fitBounds(MAP_LAYER.getBounds(),{padding:[15,15]});
  $('mapHome').onclick=()=>{LEAFLET_MAP.fitBounds(MAP_LAYER.getBounds(),{padding:[15,15]});};
  $('mapSearch').addEventListener('change',e=>{const q=e.target.value.trim().toLocaleLowerCase();if(!q)return;const f=BOUNDARIES.features.find(f=>f.properties.name.toLocaleLowerCase().includes(q)||f.properties.code.toLocaleLowerCase().includes(q));if(f)selectMapPbt(f.properties.code)});
 }
 MAP_LAYER.eachLayer(layer=>{const code=layer.feature.properties.code,n=counts[code]||0;layer.setStyle({color:code===selected?'#ffd166':'#ffffff',weight:code===selected?4:1.8,fillColor:n===0?'#a6b5c8':n/max>=.7?'#b20f30':n/max>=.4?'#ed5366':'#ffb1bb',fillOpacity:n===0?.2:.56});layer.bindTooltip(esc(layer.feature.properties.name)+'<br>'+n+' rayuan',{sticky:true})});
 const features=BOUNDARIES.features;
 summary.innerHTML='<div class="map-total"><strong>'+filtered.length+'</strong><span>Rayuan dipaparkan</span></div><p class="muted">Klik kawasan PBT pada peta satelit atau pilih PBT di bawah.</p><div class="map-pbt-list">'+features.map(f=>{let c=f.properties.code,n=counts[c]||0;return '<button class="map-pbt-row '+(selected===c?'active':'')+'" data-pbt="'+esc(c)+'"><span>'+esc(f.properties.name)+'</span><b>'+n+'</b></button>'}).join('')+'</div><button class="smallbutton map-clear" data-pbt="">Papar semua PBT</button>';
 if(MAP_POPUP_PBT)showPbtPopup(MAP_POPUP_PBT);else if($('mapPopup'))$('mapPopup').hidden=true;
 setTimeout(()=>LEAFLET_MAP.invalidateSize(),0);
}

document.addEventListener('click',e=>{const b=e.target.closest('[data-pbt]');if(b&&b.closest('#pbtMap, #pbtMapSummary')){selectMapPbt(b.dataset.pbt)}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('#pbtMap [data-pbt]')){e.preventDefault();MAP_POPUP_PBT=e.target.dataset.pbt;$('pbt').value=e.target.dataset.pbt;render()}});
fetch('pbt-boundaries.geojson').then(r=>{if(!r.ok)throw Error('Fail peta tidak ditemui');return r.json()}).then(g=>{BOUNDARIES=g;renderPbtMap()}).catch(e=>{if($('pbtMap'))$('pbtMap').textContent='Tidak dapat memuatkan peta: '+e.message});
